services:
  - type: web
    name: pro-hospital-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PASSWORD_RESET_EXPIRY_MINUTES
        value: 30
      - key: ADMIN_EMAIL
        value: admin@example.com
